function grad_E1_p2p = grad_E_pen_p2p(in1)
%grad_E_pen_p2p
%    grad_E1_p2p = grad_E_pen_p2p(IN1)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    04-Sep-2024 17:55:22

Delta = in1(:,13);
h = in1(:,14);
x1s1 = in1(:,1);
x1s2 = in1(:,2);
x1s3 = in1(:,3);
x2s1 = in1(:,7);
x2s2 = in1(:,8);
x2s3 = in1(:,9);
t2 = Delta.*2.0;
t3 = h.*4.0;
t5 = -x2s1;
t6 = -x2s2;
t7 = -x2s3;
t4 = -t3;
t8 = t5+x1s1;
t9 = t6+x1s2;
t10 = t7+x1s3;
t11 = abs(t8);
t12 = abs(t9);
t13 = abs(t10);
t14 = sign(t8);
t15 = sign(t9);
t16 = sign(t10);
t17 = t2+t4;
t18 = t11.^2;
t19 = t12.^2;
t20 = t13.^2;
t21 = t18+t19+t20;
t22 = 1.0./sqrt(t21);
t23 = t11.*t14.*t17.*t22;
t24 = t12.*t15.*t17.*t22;
t25 = t13.*t16.*t17.*t22;
grad_E1_p2p = [t23,t24,t25,0.0,0.0,0.0,-t23,-t24,-t25,0.0,0.0,0.0];
