function grad_E2_p2p = grad_E_con_p2p(in1)
%grad_E_con_p2p
%    grad_E2_p2p = grad_E_con_p2p(IN1)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    04-Sep-2024 17:55:24

Delta = in1(:,13);
K1 = in1(:,15);
h = in1(:,14);
x1s1 = in1(:,1);
x1s2 = in1(:,2);
x1s3 = in1(:,3);
x2s1 = in1(:,7);
x2s2 = in1(:,8);
x2s3 = in1(:,9);
t2 = h.*2.0;
t3 = 1.0./K1;
t5 = -x2s1;
t6 = -x2s2;
t7 = -x2s3;
t4 = -t2;
t9 = t5+x1s1;
t10 = t6+x1s2;
t11 = t7+x1s3;
t8 = Delta+t4;
t12 = abs(t9);
t13 = abs(t10);
t14 = abs(t11);
t15 = sign(t9);
t16 = sign(t10);
t17 = sign(t11);
t18 = K1.*t8;
t19 = t12.^2;
t20 = t13.^2;
t21 = t14.^2;
t22 = -t18;
t27 = t19+t20+t21;
t23 = exp(t22);
t28 = 1.0./sqrt(t27);
t24 = t23+1.0;
t25 = log(t24);
t26 = 1.0./t24;
t29 = t3.*t12.*t15.*t23.*t25.*t26.*t28.*2.0;
t30 = t3.*t13.*t16.*t23.*t25.*t26.*t28.*2.0;
t31 = t3.*t14.*t17.*t23.*t25.*t26.*t28.*2.0;
grad_E2_p2p = [-t29,-t30,-t31,0.0,0.0,0.0,t29,t30,t31,0.0,0.0,0.0];
